config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#home'
  get '/terms', to: 'top_pages#terms'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :edit_password, :following, :followers
      patch :update_password
    end
  end
  resources :microposts, only: [:create, :destroy, :new, :show] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :content, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = "コメントを投稿しました"
      redirect_to micropost_path(@micropost)
    else
      render 'microposts/show'
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    flash[:success] = "コメントを削除しました"
    redirect_to @micropost
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/views/comments/_comment.html.erb
<section class="comments">
  <li id="comment-<%= comment.id %>">
    <span class="content">
      <%= link_to set_profile_image(comment.user), comment.user %>
      <%= comment.content %>
    </span>
    <span class="timestamp">
      <p><%= time_ago_in_words(comment.created_at) %>前</p>
      <% if current_user?(comment.user) %>
        <%= link_to '削除', micropost_comment_path(comment, comment_id: comment.id), method: :delete %>
      <% end %>
    </span>
  </li>
</section>