config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#home'
  get '/terms', to: 'top_pages#terms'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :edit_password, :following, :followers
      patch :update_password
    end
  end
  resources :microposts, only: [:create, :destroy, :new, :show] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase
  REGEX_ADDRESS_VALID = /\A[\w+\-.]+@[a-z]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :user_name, presence: true, length: { maximum: 50 },
            uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: REGEX_ADDRESS_VALID },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :introduction, length: { maximum: 300 }
  validates :web_url, length: { maximum: 50 }
  validate :profile_image_size
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :comments
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :profile_image, ProfileImageUploader

#与えられた文字列のダイジェストを返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
                              BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

#ログインユーザのfeedを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                                  OR user_id = :user_id", user_id: id)
  end

#ユーザをフォローする
  def follow(other_user)
    following << other_user
  end

#フォローを解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

#ログインユーザがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  private
    def email_downcase
      self.email.downcase!
    end

#アップロードされた画像のサイズをバリデート
    def profile_image_size
      if profile_image.size > 5.megabytes
        errors.add(:profile_image, "should be less then 5Mb")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update,
                                      :edit_password, :update_password, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      flash[:success] = "登録完了しました。"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを変更しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit_password
  end

  def update_password
    if check_present_password
      flash[:success] = "パスワードを変更しました"
      redirect_to @user
    else
      flash[:danger] = "やり直してください"
      render 'edit_password'
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    @user.destroy
    logout
    flash[:success] = "アカウントを削除しました"
    redirect_to root_url
  end

  def following
    @title = "フォローユーザー"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :user_name, :profile_image,
                                   :introduction, :web_url)
    end

#入力値と現在のパスワードがあっていればtrueを返す
    def check_present_password
      @user.authenticate(params[:present_password]) &&
      params[:user][:password] != nil &&
      @user.update_attributes(user_params)
    end

#beforeフィルター

#正しいユーザーでなければルートへリダイレクト
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to root_url
      end
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit 'フォロー', class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end%>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                      html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit 'フォロー解除', class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= set_profile_image(user) %>
  <%= link_to user.name, user %>
<li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール変更") %>
<h1>プロフィール変更</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %> ※必須
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :user_name, "ユーザーネーム" %> ※必須
      <%= f.text_field :user_name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %> ※必須
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :profile_image, "プロフィール画像" %>
      <%= f.file_field :profile_image, class: "form-control", accept: 'image/jpeg,image/png' %>

      <%= f.label :introduction, "自己紹介" %> (300字以内)
      <%= f.text_area :introduction, class: 'form-control' %>

      <%= f.label :web_url, "ウェブサイト" %>
      <%= f.url_field :web_url, class: 'form-control' %>

      <%= f.submit "変更を保存", class: "btn btn-primary" %>
    <% end %>
    <%= link_to 'パスワード変更', edit_password_user_path(@user) %> ・
    <%= link_to "アカウント削除", @user, method: :delete,
                                      data: { confirm: "アカウントを削除しますか？" } %>
  </div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, "パスワード変更") %>
<h1>パスワード変更</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag update_password_user_path(@user), method: "patch" do %>
      <%= render 'shared/error_messages', object: @user %>

      <%= label_tag :present_password, "現在のパスワード" %>
      <%= password_field_tag :present_password %>

      <%= label_tag "user[password]", "新しいパスワード" %>
      <%= password_field_tag "user[password]" %>

      <%= label_tag "user[password_confirmation]", "新しいパスワードの確認" %>
      <%= password_field_tag "user[password_confirmation]" %>

      <%= submit_tag "変更を保存", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "ユーザー一覧") %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, "新規登録") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :user_name, "ユーザーネーム" %>
      <%= f.text_field :user_name, class: "form-control" %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
    <%= link_to '利用規約', terms_path %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= set_profile_image(@user) %>
        <%= @user.name %>
      </h1>
      <p>ユーザーネーム：<%= @user.user_name %></p>
        <% if current_user?(@user) %>
        <%= link_to "編集", edit_user_path(@user) %> ・
        <%= link_to "削除", @user, method: :delete,
                                    data: { confirm: "アカウントを削除しますか？" } %>
        <% end %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <p><%= @user.introduction %></p>
    <p><%= link_to @user.web_url, @user.web_url, target: :_blank %></p>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <%= render @microposts %>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= set_profile_image @user %>
      <h1><%= @user.user_name %></h1>
      <span><%= link_to "プロフィール", @user %></span>
      <span><b>投稿数：</b><%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to set_profile_image(user,size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>