config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#home'
  get '/terms', to: 'top_pages#terms'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :edit_password, :following, :followers
      patch :update_password
    end
  end
  resources :microposts, only: [:create, :destroy, :new, :show] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    フォロー
    <strong id="following" class="stat">
      <%= @user.following.count %>人
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    フォロワー
    <strong id="followers" class="stat">
      <%= @user.followers.count %>人
    </strong>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to set_profile_image(current_user), current_user %>
<h1><%= current_user.user_name %></h1>
<span><%= link_to "プロフィールへ", current_user %></span>
<span><%= current_user.microposts.count %>件の投稿</span>