config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#home'
  get '/terms', to: 'top_pages#terms'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :edit_password, :following, :followers
      patch :update_password
    end
  end
  resources :microposts, only: [:create, :destroy, :new, :show] do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <p><%= link_to "写真をアップロード",   new_micropost_path %></p>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
</head>

app/views/layouts/_header_for_logged_in.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "insta_app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ユーザー", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", current_user %></li>
            <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "ログアウト", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header_for_non_logged_in.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "insta_app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <% if logged_in? %>
      <%= render 'layouts/header_for_logged_in' %>
    <% else %>
      <%= render 'layouts/header_for_non_logged_in' %>
    <% end %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' if logged_in? %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>